### ISSUE TITLE
About self.ind

### ISSUE THREAD

**Issue by MPhone1000** [XudongLinthu/context-gated-convolution#1]
At line 19 in `context-gated-convolution/image-classification/models/layers.py`,
```
if kernel_size == 1 or True:
    self.ind = True
```
`self.ind` is always True and the layer works the same as traditional convolution.

Is `or True` redundant?

**Comment by zzwei1** [comment]
> Is `or True` redundant

same question

**Comment by XudongLinthu** [comment]
Yes, you are right, should remove "or True". I added that for sanity checks. Thanks for the comments!
