### ISSUE TITLE
about GPU comsumption

### ISSUE THREAD

**Issue by NuckyJ** [XudongLinthu/context-gated-convolution#4]
Hello, I find your job very creative and utilize it on my network. However, the GPU consumption enlarges four times as the former network when training. Have you ever encountered this problem and how can I address it? Thank you very much for your reply!

**Comment by chenjiachengzzz** [comment]
hello, can you solve this problem (too much GPU consumption)

**Comment by NuckyJ** [comment]
惠书敬悉，迟复为歉！

**Comment by XudongLinthu** [comment]
Dear all, 
Thanks for the question and sorry for the late reply. We did have similar GPU consumption issue on our side. We have identified the bottleneck to be using the unfold function and matmul to perform convolution. However, to over come this issue, it may require customized CUDA function. We don't have a plan for supporting this customized function yet.
